blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/rama1997/More-Like-This/discussions
    about: "For questions, ideas, or general conversation not suited for an issue."
