name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "more-like-this"
          token: ${{ secrets.GITHUB_TOKEN }}
