name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "more-like-this"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Docker Image Publish
        if: ${{ steps.release.outputs.release_created }}
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN || secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-docker-release
          client-payload: '{"ref": "main"}'
