name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: "more-like-this"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Docker Image Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.release.outputs.tag_name }}
        run: |
          echo "Triggering Docker workflow for tag $TAG_NAME"
          gh workflow run "release-docker.yml" \
            --repo "${GITHUB_REPOSITORY}" \
            -f ref="${TAG_NAME}"
